### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by bodunov** [usnistgov/jsip#10]
The library cannot be compiled with Java 8 compiler.

For example, one of the compilation errors:
[jain-javac] jsip/src/gov/nist/core/MultiMap.java:35: error: remove(Object,Object) in MultiMap clashes with remove(Object,Object) in Map
[jain-javac]     public Object remove( Object key, Object item );
[jain-javac]                   ^
[jain-javac]   return type Object is not compatible with boolean

As Java 8 added remove(Object,Object) method to Map class.
(also source/target value 1.5 is obsolete).

**Comment by vladimirralev** [comment]
I see. Will do. Thanks. 1.5 is obsolete but we gain nothing by dropping it at this point as far as I know.
