### ISSUE TITLE
NoSuchElementException when parsing multipart SIP content

### ISSUE THREAD

**Issue by ryanc1024** [usnistgov/jsip#16]
I have encountered an issue recently within the [MultipartMimeContentImpl](https://github.com/usnistgov/jsip/blob/master/src/gov/nist/javax/sip/message/MultipartMimeContentImpl.java#L124).  It appears that some specifically sized content can trigger a NoSuchElementException while the code is scanning through.  Looking into how the scanner works, it seems that a specifically sized piece of content could be read into the buffer with the final region end bytes not read ("--\r\n" remains on the stream yet to be read).  The pattern used by the Impl class considers them optional and matches the region.  Since there are remaining bytes and there is a matching pattern in the buffer, the Scanner returns "true" that there is another element during the hasNext() check.  Unfortunately, the Scanner reads in the final region end bytes, hits the EOF, and determines that there are no more elements (throwing the exception).

Seems like the easiest solution would be to try-catch the call to scanner.next() and breaking out of the loop when the exception is thrown.  This may not account for conditions where the body content is malformed.

I have attached an example piece of body content that throws the exception when passed into the Impl.
[jain-sip bad SIP body.txt](https://github.com/usnistgov/jsip/files/526060/jain-sip.bad.SIP.body.txt)

**Comment by vladimirralev** [comment]
I see . Looks like a valid issue. Will check it out. Thanks.

**Comment by joecarley** [comment]
@vladimirralev 
I just wanted to follow up on this issue.  Unfortunately it is affecting one of our major customers in production who are recording calls via SIPREC.  When this issue is encountered they are unable to establish the recording leg and are therefore missing recordings.
I would greatly appreciate anything you can do to look into this issue.
Thanks!

**Comment by vladimirralev** [comment]
OK, I think your idea works and tests look good. Let's see how it does.

**Comment by ryanc1024** [comment]
@vladimirralev I see that a fix was merged in and a [new build](https://jsip.ci.cloudbees.com/job/jsip/), but the build number seems off.  Is it supposed to be "1.2.**1111**"?

**Comment by vladimirralev** [comment]
OK yes the version string seems off but the binary is fine, you can use it. I will fix the build version string later.

**Comment by ranganathanm** [comment]
The version substring used to be generated from the svn version. It should be changed to the git version (should be easier to generate that).

Ranga.

**Comment by ryanc1024** [comment]
@ranganathanm are you saying the version number is correct as-is with 1.2.1111?  We are testing the current binaries, but are holding off deploying until we understand whether the versioning is correct to match repo pin.

**Comment by ranganathanm** [comment]
Hello,

This code was ported from SVN. The version number was (previously) generated from the SVN version number. Since the code moved from SVN to github, the version number generator has not been updated.

BR

Ranga.

**Comment by jagliot** [comment]
I've encountered the same issue when trying to run the tests on the jain sip stack. The bug is caused by a jvm bug: https://bugs.openjdk.java.net/browse/JDK-8139414. I'll try and find a fix

**Comment by ryanc1024** [comment]
Confirmed that the try-catch resolves the issue.
