### ISSUE TITLE
PAccessNetworkInfoParser incomplete

### ISSUE THREAD

**Issue by hphalle** [usnistgov/jsip#20]
The syntax for the P-Access-Network-Info contains a gen-value as a choice for access-info. gen-value is defined as "token / host / quoted-string". So the following header lines are syntactically OK but they will be rejected by the current parser implementation:

P-Access-Network-Info: 3GPP-UTRAN-TDD; utran-cell-id-3gpp=23456789ABCDE;"ip=123.123.123.123"
P-Access-Network-Info: 3GPP-UTRAN-TDD; utran-cell-id-3gpp=23456789ABCDE; [123:4::abcd]

**Comment by vladimirralev** [comment]
Yes, agreed.

`gen-value              =  token / host / quoted-string`

WIll add it, thanks.
