### ISSUE TITLE
call transfer

### ISSUE THREAD

**Issue by mizutechvoip** [usnistgov/jsip#24]
I am trying to use call transfer. Caller endpoint is a test jsip implementation. Called endpoint is the mizu [java sip client](https://www.mizu-voip.com/Software/Softphones/JVoIP.aspx). jsip doesn't seems to send any SIP REFER message. Is call transfer implemented in this lib?

**Comment by vladimirralev** [comment]
Sending and receiving REFER is supported, but of course jsip itself doesn't implement the transfer RFCs. It is up to you to compose the actual REFER message depending on the type of transfer you need. If you are composing and sending REFER from your code but still have a problem, post some code and/or debug logs and I will check it out.

**Comment by mizutechvoip** [comment]
Thank you, I am testing... (The problem is that it is very hard to handle the notifications about transfer state with no high level support for it)

**Comment by vladimirralev** [comment]
Well, there are at least 10 types of transfer in different RFCs. Some are very complicated, but basic transfer is fairly simple. I have some code here I use for blind transfer on a dialog, that's all I have to do:
```
	public void sendRefer(String to) {
		Request req = dialog.createRequest("REFER");
		req.addHeader(headerFactory.createHeader("Refer-To", "sip:"+to+"@"+realm));
		req.addHeader(headerFactory.createHeader("Referred-By", "sip:"+user+"@"+realm));
		dialog.sendRequest(provider.getNewClientTransaction(req));
	}
```

**Comment by ranganathanm** [comment]
What notifications about transfer state are you talking about? These are indicated indirectly using Transaction and Dialog state.


There's some support to let you track per dialog or per transaction state. Look at the AppData (set / get) for Transaction and Dialog. That's a convenient way of keeping track of per dialog/transaction state without having to deal with hash tables and garbage collection.


Ranga


________________________________

**Comment by mizutechvoip** [comment]
Thank you for the code example.

(On notifications I mean SIP NOTIFY messages which might be sent from the other peer about transfer call status ...with the sip answers in the NOTIFY body, such as ringing, 200 connected / 4xx failed)

**Comment by ranganathanm** [comment]
Sorry, I meant there's some support allowing you to associate application state with dialog/transaction state. The stack tracks tx and dialog state.


Ranga

________________________________
