### ISSUE TITLE
Kill this repo and transfer ownership of RestComm/jain-sip to usnistgov

### ISSUE THREAD

**Issue by ibauersachs** [usnistgov/jsip#3]
Please consider dropping this repository and taking ownership of RestComm/jain-sip.

There are numerous forks of RestComm/jain-sip on Github and it has been the de-facto master of jsip for a long time. Commits in the SVN repo at Kenai have long been referencing pull requests and issues of RestComm/jain-sip. I'd consider it a major disaster to have two competing jsip repos.

Having RestComm/jain-sip as the master has the clear benefit that
- All forks on Github will still be based on the then de-jure official jsip
- All issues and pull requests in the commit log will refer to the correct links

I don't know if this has been up for discussion and dismissed earlier and if so I'm sorry.

**Comment by vladimirralev** [comment]
I see the problem, but it's a bit better to have a neutral root repository. It will be more difficult for jain-sip developers to do business if we have to link up to a competitor-branded repository. Use of alternative issue trackers has always been discouraged and it's up to the committers. NIST has been a good neutral party helping this project, we can respect that.

**Comment by ibauersachs** [comment]
I don't quite understand the branded repository part? If the RestComm repository would be transferred to NIST, there would be no branding left. Github even automatically redirects to the new location. Of course RestComm would need to agree to that, but given that most or all committers there had SVN commit access too I doubt that there would be a big problem.

**Comment by ranganathanm** [comment]
Speaking for NIST, it is not possible for NIST to assume ownership of RestComm, given the fact that it is owned by TeleStax, who may want to build "differentiators" over and above the base stack code. On the other hand, it would be great if telestax could push non-proprietary updates to usnistgov/jsip (by generating pull requests). I would consider that an act of good citizenship.


Regards,


Ranga



________________________________

**Comment by deruelle** [comment]
Pull requests can be done indeed. 

The bigger question here is how does the community want this project to evolve ? There is a number of things that we are planning to evolve for JAIN SIP such as proper maven directory structure and usage, netty integration, logging upgrade, deeper structural changes to improve performance which have all been disapproved in the past.

I'll let @jaimecasero comment more on that as he has taken over the SIP leadership on the Restcomm side.

**Comment by ibauersachs** [comment]
As a side note, Jitsi (where I was recently updating jsip), is using a jsip fork based on RestComms repo because of the Maven support and being on Github for a long time.

(Btw. we're using a fork because the plain jsip repo (either from NIST or from RestComm) cannot be used in open source projects because of the non-free javax.* headers. So if jsip is ever going to be packaged for e.g. Debian, it's likely to be based on Jitsi's or some other fork (unless someones manages to remove the non-free headers here).)

**Comment by deruelle** [comment]
Right. Again, the git move was more done as reactive because java.net closed down rather than being proactive. 
Can you expand on the non-free javax headers and what you had to do to allow packaging for Debian ?

**Comment by ibauersachs** [comment]
We haven't done any independent packaging for Debian yet, but libjitsi, which included jsip, was rejected because of those headers. We migrated jitsi/ice4j, jitsi/libjitsi and jitsi/jitsi to use @dpocock's header re-implementation at opentelecoms-org/java-sip-api, opentelecoms-org/java-sdp-api and opentelecoms-org/java-sdp-nist-bridge.
Btw, Android reimplemented these headers as well (probably by simply doing a refactoring with "extract interface" and they are thus not really usable).

**Comment by ranganathanm** [comment]
Hi all,


The Oracle owned headers should all be OK AFIK (FWIW and other defensive acronyms apply here). It is no more restrictive than java itself AFIK.


If you are concerned about the sdp headers, somebody can just strip the SDP interfaces from the distro. It should be fairly easy to do and I believe Google already did that


I do not mind accepting header re-implementations provided they are cleanly separable. i..e  You can do a different class path and supply interfaces with the same functionality.


I am not doing much with SIP these days, so if anybody steps up to that, then I'd be happy to put it in the repo.


Sometimes you do wish java had ifdefs.


#ifndef RANGA

#define RANGA


Best regards,


Ranga


#endif




________________________________

**Comment by ibauersachs** [comment]
The IANAL, FWIW and so on don't help: as long as the header says something that isn't compatible with DFSG (Debian Free Software Guidelines) it won't go into Debian, be it SDP or SIP.

Just stripping the SDP headers is not possible because it references the SDP implementation from within the headers. The headers shipped with jsip also have additional methods that aren't defined in the JSR and SdpFactory is a class instead of an interface.

But this really is a separate issue and doesn't address the mess of repository that will arrive if this one here is continuing to exist and evolve.

**Comment by ranganathanm** [comment]
Thanks for bringing this up. I guess I need to explain why this repo exists.


The repo here is really here because it serves as a public domain resource. It is here because anybody can build proprietary extensions using this as a basis and not have to worry about licensing changes. It is here because NIST "owns" this little corner of github and makes that promise to the world (thats why this lives in the usnistgov organization). According to public domain, nothing prevents anybody from "copyrighting" and changing the license of a derivative work although the original remains in the public domain. That is why NIST hosts this and other repositories. If the code were unavailable, and say some company X were the only ones who had the code, they could change the license on you tomorrow and nobody would be able to sue them (NIST would not sue them anyway).


The "problem" (as you term it) is really the other way around. This is the so called "original" repository.  Forks of this repository should push non-proprietary changes upstream. Folks are encouraged to be good citizens and contribute non-proprietary changes to this repository.


What is IANAL (ahem... not sure what that means)?


You can always re-implement the SDP Factory interfaces.


I have no control over the original licensing of JSIP interfaces. Note that they belong to Oracle.


________________________________

**Comment by GregDThomas** [comment]
A related question; there's an artefact at https://mvnrepository.com/artifact/javax.sip/jain-sip-ri which suggests it's the Reference Implementation - but it's updated far more recently than either of the repo's mentioned in this thread. Is there a third repo somewhere?

**Comment by murphy-li** [comment]
As far as now, The repo  RestComm/jain-sip has not been update for a long time.
