### ISSUE TITLE
NPE stopping SIP Stack after JVM Bind Exception

### ISSUE THREAD

**Issue by ryanc1024** [usnistgov/jsip#31]
Recently encountered this issue when attempting to stop the SipStack.  It looks like a missing null check within the TCPMessageProcessor class when the socket fails to be created.  In my case, the designated port was already in use, so we get a JVM bind error creating the listening port.

```
[SipManager|2214|E] 2018-01-25 11:47:17.704-05:00  SipManager<10, :[5071]> caught Exception<javax.sip.InvalidArgumentException: Address already in use: JVM_Bind> while starting
[SipManager|2214|E] 2018-01-25 11:47:17.704-05:00  javax.sip.InvalidArgumentException: Address already in use: JVM_Bind Message<Address already in use: JVM_Bind> Cause<java.net.BindException: Address already in use: JVM_Bind>
[SipManager|2214|E] 2018-01-25 11:47:17.704-05:00     gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1552)
```
If I call stop on the SipStack after this, a NullPointerException is thrown.

```
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00  Failed To Stop SipStack java.lang.NullPointerException
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00  java.lang.NullPointerException
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00     gov.nist.javax.sip.stack.TCPMessageProcessor.stop(TCPMessageProcessor.java:164)
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00     gov.nist.javax.sip.stack.SIPTransactionStack.removeMessageProcessor(SIPTransactionStack.java:2422)
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00     gov.nist.javax.sip.stack.SIPTransactionStack.stopStack(SIPTransactionStack.java:2110)
[SipManager|339C|E] 2018-01-25 11:47:18.494-05:00     gov.nist.javax.sip.SipStackImpl.stop(SipStackImpl.java:1711)
```
This interruption of the stop() leaves at least two (2) threads on the system related to the SipStack: EventScannerThread and Timer-_n_.

Reviewing the source, it looks like the TCPMessageProcessor is not checking that the socket is valid before calling close().  I suspect the socket is null because of the previous binding error.

I tried the same scenario with UDP ports and did not have the same issue.  As a workaround, I found that a _second_ call to stop() does close out the remaining threads.

**Comment by vladimirralev** [comment]
Ha, thanks. I will check it out on the weekend.
