### ISSUE TITLE
Option to Enable TCP_NODELAY

### ISSUE THREAD

**Issue by namiles** [usnistgov/jsip#37]
TCP SIP applications using Jain SIP can suffer from poor response times because its TCP sockets do not have Nagle's algorithm disabled.

There should at least be an option to set TCP_NODELAY for an application, but I think that TCP_NODELAY should be the default behavior. At the very least, there should be an option.

It's pretty easy to do. `Socket` instances just need `newsock.setTcpNoDelay(true)`.

Edit: I'm willing to do the development on this if you want to add this feature.

**Comment by vladimirralev** [comment]
Sounds reasonable. Yes please go ahead and do a pull request. I will check it out and adapt it to the NIO.

**Comment by ranganathanm** [comment]
Concur with Vlad.

**Comment by vladimirralev** [comment]
I would suggest to use the property gov.nist.javax.sip.TCP_NODELAY = [true|false] so that it's in the correct style for a nist extension.

**Comment by namiles** [comment]
Hey guys, somehow didn't notice that you had responded. I just submitted [this PR](https://github.com/usnistgov/jsip/pull/41).

**Comment by namiles** [comment]
[PR merged](https://github.com/usnistgov/jsip/pull/41)
