### ISSUE TITLE
dedication to the public domain

### ISSUE THREAD

**Issue by tkphd** [usnistgov/jsip#38]
Per the [Public Repository Guidelines](http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines), please add a `LICENSE` 
file containing the  approved [statement](https://www.nist.gov/director/copyright-fair-use-and-licensing-statements-srd-data-and-software#software) in compliance with [17USC§105](https://www.govinfo.gov/content/pkg/USCODE-2014-title17/pdf/USCODE-2014-title17-chap1-sec105.pdf).

**Comment by vladimirralev** [comment]
Done https://github.com/usnistgov/jsip/blob/master/LICENSE
