### ISSUE TITLE
NPE in DefaultSecurityManagerProvider if no trustStorePassword supplied

### ISSUE THREAD

**Issue by m0thra** [usnistgov/jsip#44]
Encountered if supplying a javax.net.ssl.trustStore and NOT supplying a javax.net.ssl.keyStorePassword

`Caused by: java.lang.NullPointerException
        at gov.nist.core.net.DefaultSecurityManagerProvider.init(DefaultSecurityManagerProvider.java:98)
        at gov.nist.javax.sip.SipStackImpl.<init>(SipStackImpl.java:1133)`

```java
if(trustStoreFilename != null) {
	final KeyStore ts = KeyStore.getInstance(trustStoreType);
	ts.load(new FileInputStream(new File(trustStoreFilename)), trustStorePassword.toCharArray());
	
	trustManagerFactory.init((KeyStore) ts);
} else {
	trustManagerFactory.init((KeyStore)null);
}
```

**Comment by m0thra** [comment]
Fix is probably just to make the first line of the code above to be `if(trustStoreFilename != null && trustStorePassword != null)`

**Comment by vladimirralev** [comment]
Hmm right. I will check it out. Thanks.
