### ISSUE TITLE
Expires and Min-Expires SIP headers break for large values

### ISSUE THREAD

**Issue by p-ma** [usnistgov/jsip#60]
RFC 3261 defines the contents of the Expires and Min-Expires headers in SIP as "an integral number of seconds (in decimal) between 0 and (2^32)-1".
(https://tools.ietf.org/html/rfc3261#section-20.19)
This can be represented as an unsigned 32-bit integer, but since java uses signed integers, only values up to (2^31)-1 can be used without errors.

In the usual time-related context, this wouldn't be much of a problem, since we're talking about absurdly high values anyway. However, 3GPP's MCX/MCPTT protocol, which is based on SIP, requires the maximum allowed value of 4,294,967,295 to be used in the Expires header for certain messages. The reasons for this are beyond me, but obviously those messages will cause trouble.

I fixed the problem for me, locally, by changing the types from int to long, and restricting input values to the correct range. Didn't have any problems since. I'll try to attach a PR (bear with me, I'm new to the github stuff). Note that the error starts with the JSIP API interface definitions, so those would need changes too, and I don't know if that's easily possible (license issues etc). Ultimately, I won't mind if you ignore this issue. I just wanted to inform you of this and propose a fix, since I saw there's still some activity in here (which is nice).

**Comment by vladimirralev** [comment]
Hmm. I see, this seems valid, but indeed changing the javax.* interface is probleamtic.

 #61 

The safe thing to do is to use an interface that is in the gov.nist package like the *Ext classes in gov.nist.javax.sip. For the original javax.sip.* interfaces cast everything to int so that it keeps working against old code. 

If you can, please do that, otherwise I will see when I can integrate it, possibly behind an adapter.

**Comment by p-ma** [comment]
Thanks for the quick reply.

I'm not sure if I completely understand what you're asking, but I tried my best.
I added overloaded methods for setters, and introduced new getter methods ("Long" appended), to retrieve the correct value. Also tried to chang the rest of the RI to only use those methods, instead of the API-defined ones. Getting the int value with the old method will return Integer.MAX_VALUE if it's out of range (not sure what makes the most sense here, maybe you can tell).

I hope this might be an agreeable solution, or at least go in the right direction.

**Comment by vladimirralev** [comment]
Yes I think that looks agreeable, I will read it later, may take a few days, but yes the point is to keep the javax interface and only expose the Long in private as part of the nist API. Thank you.
