### ISSUE TITLE
jsip is checking the sdp from the final response and not from provisional response

### ISSUE THREAD

**Issue by cfdomingues** [usnistgov/jsip#62]
SIPServerTransactionImpl.java line 1452 you test the sdp from the final response and you must check the session description from provisional response.

/*
 * The UAS MAY send a final response to the initial request before
 * having received PRACKs for all unacknowledged reliable provisional responses,
 * unless the final response is 2xx and any of the unacknowledged reliable provisional
 * responses contained a session description. In that case, it MUST NOT send a final
 * response until those provisional responses are acknowledged.
 */

As you put in description, an user agent can send a final response after an unacked provisional if the unacknowledged reliable provisional responses doesn't contained a session description.

**Comment by vladimirralev** [comment]
Hmm. I couldn't quite grasp what is the issue. Line https://github.com/usnistgov/jsip/blob/master/src/gov/nist/javax/sip/stack/SIPServerTransactionImpl.java#L1452 doesn't have anything to do with SDP or provisional responses. It's inside a dialog-stateful context only.

**Comment by cfdomingues** [comment]
Hi vladimirralev, in your revision there is in line is 1403.
I report it in https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/stack/SIPServerTransactionImpl.java#L1452
sorry for not specify it

**Comment by vladimirralev** [comment]
I see, yes looks like we need to check the SDP of the provisional response instead of the final response we attempt to send. I'll try to fix that.
